format = """\
[$username](fg:red)\
[$directory](fg:cyan)\
[$git_branch$git_status](fg:green)$battery
$time(fg:white)$character
"""

# Left Prompt
# [username]
# show_always = true
# format = ' $user '

[directory]
truncation_length = 3
truncation_symbol = "… "
format = '$path$read_only'

[git_branch]
symbol = ""
format = ' $symbol $branch(:$remote_branch)'

[git_status]
deleted = "X"
format = '\[$all_status$ahead_behind\]'

[character]
success_symbol = "[ ](fg:green)"
error_symbol = "[ ](fg:red)"


# Right Prompt
[time]
disabled = false
format = '[$time](fg:white)'

[battery]
full_symbol = '󰁹'
charging_symbol = '󰂄'
discharging_symbol = '󱟤'
format = '[ $symbol $percentage](fg:yellow)'
[[battery.display]]
threshold = 100
