-- return {
-- 	dir = "~/Desktop/feedback.nvim",
-- 	config = function()
-- 		require("feedback").setup({
-- 			flash_time = 150, -- 閃爍持續時間（毫秒）
-- 			color = "#ffffff", -- 閃爍顏色（淺綠色）
-- 			alpha = 10,     -- 透明度 (0-100)
-- 		})
-- 	end,
-- }
return {}
