[tools]
bun = "latest"
gleam = "latest"
go = "1.25"
java = "temurin-25.0.2+10.0.LTS"
neovim = "nightly"
node = "24"
pipx = "latest"
pnpm = "latest"
python = "3.14"
rust = "nightly"
wasmtime = "latest"
zig = "0.16.0"
zls = "0.16.0"
